name: Chaos

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Creating kind cluster 
      uses: helm/kind-action@v1.0.0-rc.1

    - name: Print cluster information
      run: |
        kubectl config view
        kubectl cluster-info
        kubectl get nodes
        kubectl get pods -n kube-system
        helm version
        kubectl version

    - uses: actions/checkout@v2

    - name: Deploy an application
      run: |
        kubectl apply -f https://raw.githubusercontent.com/chaos-mesh/apps/master/ping-baidu/busybox-statefulset.yaml
        
    - name: Check pods
      run: |
        kubectl get pods -n chaos-testing
        kubectl get pods -n busybox
        
    - name: Run chaos mesh action
      uses: WangXiangUSTC/chaos-mesh-actions@master
      env:
        CFG_BASE64: YXBpVmVyc2lvbjogY2hhb3MtbWVzaC5vcmcvdjFhbHBoYTEKa2luZDogTmV0d29ya0NoYW9zCm1ldGFkYXRhOgogIG5hbWU6IG5ldHdvcmstZGVsYXkKICBuYW1lc3BhY2U6IGJ1c3lib3gKc3BlYzoKICBhY3Rpb246IGRlbGF5ICMgdGhlIHNwZWNpZmljIGNoYW9zIGFjdGlvbiB0byBpbmplY3QKICBtb2RlOiBhbGwKICBzZWxlY3RvcjoKICAgIHBvZHM6CiAgICAgIGJ1c3lib3g6CiAgICAgICAgLSBidXN5Ym94LTAKICBkZWxheToKICAgIGxhdGVuY3k6ICIxMG1zIgogIGRpcmVjdGlvbjogdG8KICB0YXJnZXQ6CiAgICBzZWxlY3RvcjoKICAgICAgcG9kczoKICAgICAgICBidXN5Ym94OgogICAgICAgICAgLSBidXN5Ym94LTEKICAgIG1vZGU6IGFsbAo=

    - name: Verify
      run: |
        echo "do some verify"
        echo "ping from busybox-0 to busybox-1"
        kubectl exec busybox-0 -it -n busybox -- ping -c 10 busybox-1.busybox.busybox.svc
        echo "ping from busybox-1 to busybox-0"
        kubectl exec busybox-1 -it -n busybox -- ping -c 10 busybox-0.busybox.busybox.svc
